#!/usr/bin/env python3
"""Claim-free external preflight for the V11 seven-entry predecessor replay artifact.

This tool validates immutable ZIP bytes, the successor wrapper schema, child
hash bindings, frozen v1 hosted evidence semantics, and the independently
supplied predecessor/candidate/run tuple. It never admits A0, mutates GitHub,
or claims runtime/package provenance that was not reconstructed here.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import re
import stat
import sys
import unicodedata
import xml.etree.ElementTree as ET
import zipfile
from pathlib import Path
from typing import Any, NoReturn

AUTHORITY = "nxb-v11-predecessor-replay-envelope-preflight-v1"
WRAPPER_AUTHORITY = "nxb-v11-predecessor-replay-v1"
WRAPPER_SCHEMA_FILE = "nxb-v11-predecessor-replay-receipt.schema.json"
WRAPPER_SCHEMA_ID = "urn:nxb:schema:nxb-v11-predecessor-replay-receipt:v1"
WRAPPER_SCHEMA_SHA256 = "e305ff9d4e9e143f21650ed3dcdd02ceaf17542fc601ce35fc2cff3cfb7f43b8"
EXPECTED_JSONSCHEMA_VERSION = "4.26.0"

EXPECTED_NAMES = frozenset(
    {
        "hosted-ci-receipt.json",
        "known-error-scan.json",
        "pester-ps51.xml",
        "pester-ps7.xml",
        "ps51-summary.json",
        "run-ps51.ps1",
        "predecessor-replay-receipt.json",
    }
)
CHILD_HASH_FIELDS = {
    "hosted-ci-receipt.json": "hosted_ci_receipt_sha256",
    "known-error-scan.json": "known_error_scan_sha256",
    "pester-ps51.xml": "pester_ps51_xml_sha256",
    "pester-ps7.xml": "pester_ps7_xml_sha256",
    "ps51-summary.json": "ps51_summary_sha256",
    "run-ps51.ps1": "run_ps51_sha256",
}

# Canonical #26 closure authority and the final successful native/hosted evidence
# freeze both use this exact partition.
FROZEN_PS7_TOTAL = 916
FROZEN_PS51_PASSED = 909
FROZEN_PS51_NOT_RUN = 7
FROZEN_PS51_EXCLUDED_TAG = "PS7Only"

# run-ps51.ps1 is deterministically generated by the frozen v1 hosted producer.
# This digest was independently re-hashed from hosted artifact 11154280859.
FROZEN_RUN_PS51_SHA256 = (
    "035ac21a439c448be6ad6d946bd3526162f678b1858d09562b69c5616a49397b"
)

MAX_ZIP_BYTES = 8 * 1024 * 1024
MAX_ENTRY_BYTES = 2 * 1024 * 1024
MAX_TOTAL_UNCOMPRESSED = 8 * 1024 * 1024
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
GIT40_RE = re.compile(r"^[0-9a-f]{40}$")
DECIMAL_RE = re.compile(r"^[1-9][0-9]*$")
I64_MIN = -(1 << 63)
I64_MAX = (1 << 63) - 1


class PreflightError(ValueError):
    """Expected fail-closed rejection, exit status 2."""


def fail(reason: str) -> NoReturn:
    raise PreflightError(reason)


def _pairs_unique(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            fail("duplicate JSON object key")
        result[key] = value
    return result


def _parse_integer(value: str) -> int:
    number = int(value)
    if not I64_MIN <= number <= I64_MAX:
        fail("JSON integer outside signed 64-bit range")
    return number


def _parse_float(_value: str) -> NoReturn:
    fail("floating-point JSON numbers are forbidden")


def _parse_constant(_value: str) -> NoReturn:
    fail("non-finite JSON numbers are forbidden")


def _check_strings(value: Any) -> None:
    if isinstance(value, str):
        if unicodedata.normalize("NFC", value) != value:
            fail("non-NFC JSON string")
        if any(ord(char) < 0x20 or ord(char) == 0x7F for char in value):
            fail("JSON string contains a control character")
        if any(0xD800 <= ord(char) <= 0xDFFF for char in value):
            fail("JSON string contains an unpaired Unicode surrogate")
    elif isinstance(value, dict):
        for key, child in value.items():
            _check_strings(key)
            if not key.isascii():
                fail("JSON object key outside ASCII contract")
            _check_strings(child)
    elif isinstance(value, list):
        for child in value:
            _check_strings(child)


def _strict_json(content: bytes, name: str) -> dict[str, Any]:
    if content.startswith(b"\xef\xbb\xbf"):
        fail(f"{name}: UTF-8 BOM forbidden")
    try:
        decoded = content.decode("utf-8", "strict")
        document = json.loads(
            decoded,
            object_pairs_hook=_pairs_unique,
            parse_int=_parse_integer,
            parse_float=_parse_float,
            parse_constant=_parse_constant,
        )
    except (UnicodeDecodeError, ValueError, TypeError, RecursionError) as exc:
        if isinstance(exc, PreflightError):
            raise
        fail(f"{name}: invalid JSON")
    if not isinstance(document, dict):
        fail(f"{name}: JSON root must be an object")
    _check_strings(document)
    return document


def _ordinary_path(path: Path, *, directory: bool) -> None:
    if not path.is_absolute():
        fail("input path must be absolute")
    try:
        metadata = path.lstat()
    except OSError:
        fail("input path is absent or unreadable")
    expected = stat.S_ISDIR if directory else stat.S_ISREG
    if not expected(metadata.st_mode):
        fail("input path has the wrong filesystem type")
    if getattr(metadata, "st_file_attributes", 0) & getattr(
        stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400
    ):
        fail("input path reparse-point forbidden")


def _regular_zip_entry(info: zipfile.ZipInfo) -> None:
    if info.filename not in EXPECTED_NAMES:
        fail("unexpected, nested, or unsafe predecessor replay entry")
    if info.is_dir():
        fail("directory predecessor replay entry forbidden")
    if info.flag_bits & 0x1:
        fail("encrypted predecessor replay entry forbidden")
    if info.compress_type not in (zipfile.ZIP_STORED, zipfile.ZIP_DEFLATED):
        fail("unsupported predecessor replay compression method")
    if info.file_size < 0 or info.file_size > MAX_ENTRY_BYTES:
        fail("predecessor replay entry exceeds byte ceiling")
    if info.compress_size < 0 or info.compress_size > MAX_ZIP_BYTES:
        fail("predecessor replay compressed entry exceeds byte ceiling")
    if info.create_system == 3:
        unix_mode = (info.external_attr >> 16) & 0xFFFF
        if unix_mode:
            kind = stat.S_IFMT(unix_mode)
            if kind not in (0, stat.S_IFREG):
                fail("nonregular UNIX predecessor replay entry metadata")
    if info.external_attr & 0x10:
        fail("directory-attribute predecessor replay entry forbidden")
    if info.filename != unicodedata.normalize("NFC", info.filename):
        fail("non-NFC predecessor replay entry name")


def _load_wrapper_schema(schema_root: Path) -> dict[str, Any]:
    _ordinary_path(schema_root, directory=True)
    path = schema_root / WRAPPER_SCHEMA_FILE
    try:
        metadata = path.lstat()
        content = path.read_bytes()
    except OSError:
        fail("predecessor replay wrapper schema absent or unreadable")
    if not stat.S_ISREG(metadata.st_mode):
        fail("predecessor replay wrapper schema is not a regular file")
    if getattr(metadata, "st_file_attributes", 0) & getattr(
        stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400
    ):
        fail("predecessor replay wrapper schema reparse-point forbidden")
    if hashlib.sha256(content).hexdigest() != WRAPPER_SCHEMA_SHA256:
        fail("predecessor replay wrapper schema SHA-256 drift")
    schema = _strict_json(content, WRAPPER_SCHEMA_FILE)
    if schema.get("$id") != WRAPPER_SCHEMA_ID:
        fail("predecessor replay wrapper schema ID drift")
    if schema.get("$schema") != "https://json-schema.org/draft/2020-12/schema":
        fail("predecessor replay wrapper schema dialect drift")
    return schema


def _validate_wrapper_schema(
    wrapper: dict[str, Any], schema_root: Path
) -> str:
    try:
        from importlib.metadata import PackageNotFoundError, version
        from jsonschema import Draft202012Validator, FormatChecker
        from jsonschema.exceptions import SchemaError, ValidationError

        jsonschema_version = version("jsonschema")
    except (ImportError, PackageNotFoundError):
        fail("jsonschema package unavailable for predecessor replay preflight")
    if jsonschema_version != EXPECTED_JSONSCHEMA_VERSION:
        fail("jsonschema package version differs from predecessor replay pin")
    schema = _load_wrapper_schema(schema_root)
    try:
        Draft202012Validator.check_schema(schema)
        Draft202012Validator(
            schema, format_checker=FormatChecker()
        ).validate(wrapper)
    except SchemaError:
        fail("predecessor replay wrapper schema contract invalid")
    except ValidationError:
        fail("predecessor replay wrapper schema semantic validation failed")
    return jsonschema_version


def _positive_int_text(value: int, label: str) -> str:
    text = str(value)
    if DECIMAL_RE.fullmatch(text) is None:
        fail(f"{label} must be a positive decimal integer")
    return text


def _expect_sha(value: str, label: str, *, git: bool = False) -> str:
    pattern = GIT40_RE if git else SHA256_RE
    if pattern.fullmatch(value) is None:
        fail(f"{label} has invalid lowercase digest syntax")
    return value


def _xml_results(content: bytes, name: str) -> dict[str, int]:
    if b"<!DOCTYPE" in content.upper() or b"<!ENTITY" in content.upper():
        fail(f"{name}: XML DTD/entity declarations forbidden")
    try:
        root = ET.fromstring(content)
    except (ET.ParseError, ValueError, RecursionError):
        fail(f"{name}: invalid XML")
    if root.tag != "test-results":
        fail(f"{name}: unexpected NUnit root element")
    if root.attrib.get("name") != "Pester":
        fail(f"{name}: unexpected NUnit producer name")

    result: dict[str, int] = {}
    for field in (
        "total",
        "errors",
        "failures",
        "not-run",
        "inconclusive",
        "ignored",
        "skipped",
        "invalid",
    ):
        raw = root.attrib.get(field)
        if raw is None or not raw.isascii() or not raw.isdigit():
            fail(f"{name}: invalid NUnit {field} attribute")
        result[field] = int(raw)
    for field in ("errors", "failures", "inconclusive", "ignored", "skipped", "invalid"):
        if result[field] != 0:
            fail(f"{name}: NUnit failure/skip state is nonzero")
    return result


def _all_empty_known_error_findings(value: Any) -> bool:
    if isinstance(value, list):
        return len(value) == 0
    if isinstance(value, dict):
        return all(_all_empty_known_error_findings(child) for child in value.values())
    return False


def inspect_predecessor_replay(
    path: Path,
    schema_root: Path,
    expected_zip_sha256: str,
    expected_predecessor_main_sha: str,
    expected_predecessor_tree_sha: str,
    expected_observer_successor_head_sha: str,
    expected_run_id: int,
    expected_run_attempt: int,
    expected_artifact_name: str,
    expected_predecessor_policy_sha256: str,
) -> dict[str, Any]:
    _expect_sha(expected_zip_sha256, "expected ZIP SHA-256")
    _expect_sha(expected_predecessor_main_sha, "expected predecessor main SHA", git=True)
    _expect_sha(expected_predecessor_tree_sha, "expected predecessor tree SHA", git=True)
    _expect_sha(
        expected_observer_successor_head_sha,
        "expected observer successor head SHA",
        git=True,
    )
    _expect_sha(
        expected_predecessor_policy_sha256,
        "expected predecessor policy SHA-256",
    )
    run_id_text = _positive_int_text(expected_run_id, "expected run ID")
    attempt_text = _positive_int_text(expected_run_attempt, "expected run attempt")

    expected_reconstructed_name = (
        f"{WRAPPER_AUTHORITY}-{expected_predecessor_main_sha}-"
        f"{expected_observer_successor_head_sha}-{run_id_text}-{attempt_text}"
    )
    if expected_artifact_name != expected_reconstructed_name:
        fail("independently supplied predecessor replay artifact name mismatch")

    _ordinary_path(path, directory=False)
    try:
        metadata = path.lstat()
        if metadata.st_size <= 0 or metadata.st_size > MAX_ZIP_BYTES:
            fail("predecessor replay ZIP exceeds bounded size")
        archive_bytes = path.read_bytes()
    except OSError:
        fail("predecessor replay ZIP unreadable")
    if not archive_bytes or len(archive_bytes) > MAX_ZIP_BYTES:
        fail("predecessor replay ZIP exceeds bounded size")
    outer_sha256 = hashlib.sha256(archive_bytes).hexdigest()
    if outer_sha256 != expected_zip_sha256:
        fail("independently supplied predecessor replay ZIP digest mismatch")

    try:
        with zipfile.ZipFile(
            io.BytesIO(archive_bytes), mode="r", allowZip64=False
        ) as archive:
            entries = archive.infolist()
            if archive.comment:
                fail("predecessor replay ZIP comment forbidden")
            if len(entries) != len(EXPECTED_NAMES):
                fail("predecessor replay entry count is not exactly seven")
            names = [entry.filename for entry in entries]
            if len(set(names)) != len(names):
                fail("duplicate predecessor replay entry names")
            if len({name.casefold() for name in names}) != len(names):
                fail("case-colliding predecessor replay entry names")
            if set(names) != EXPECTED_NAMES:
                fail("predecessor replay entry set mismatch")
            for entry in entries:
                _regular_zip_entry(entry)
            if sum(entry.file_size for entry in entries) > MAX_TOTAL_UNCOMPRESSED:
                fail("predecessor replay uncompressed bytes exceed ceiling")

            contents: dict[str, bytes] = {}
            for entry in entries:
                try:
                    with archive.open(entry, "r") as stream:
                        content = stream.read(MAX_ENTRY_BYTES + 1)
                        if len(content) > MAX_ENTRY_BYTES or stream.read(1):
                            fail("predecessor replay entry exceeds decompression ceiling")
                except (RuntimeError, OSError, EOFError, ValueError, zipfile.BadZipFile):
                    fail("predecessor replay entry failed decompression/CRC verification")
                contents[entry.filename] = content
    except (OSError, zipfile.BadZipFile, zipfile.LargeZipFile):
        fail("malformed or unsupported predecessor replay ZIP")

    wrapper = _strict_json(
        contents["predecessor-replay-receipt.json"],
        "predecessor-replay-receipt.json",
    )
    schema_validator_version = _validate_wrapper_schema(wrapper, schema_root)

    if wrapper.get("authority") != WRAPPER_AUTHORITY:
        fail("predecessor replay wrapper authority mismatch")
    if wrapper.get("entry_count") != 7:
        fail("predecessor replay wrapper cardinality mismatch")

    child_hashes: dict[str, str] = {}
    for name, field in CHILD_HASH_FIELDS.items():
        digest = hashlib.sha256(contents[name]).hexdigest()
        child_hashes[name] = digest
        if wrapper.get(field) != digest:
            fail(f"predecessor replay child SHA-256 mismatch for {name}")

    if child_hashes["run-ps51.ps1"] != FROZEN_RUN_PS51_SHA256:
        fail("frozen predecessor run-ps51.ps1 byte identity drift")

    expected_tuple = {
        "predecessor_main_sha": expected_predecessor_main_sha,
        "predecessor_tree_sha": expected_predecessor_tree_sha,
        "observer_successor_head_sha": expected_observer_successor_head_sha,
        "run_id": expected_run_id,
        "run_attempt": expected_run_attempt,
        "artifact_name": expected_artifact_name,
        "predecessor_policy_sha256": expected_predecessor_policy_sha256,
    }
    for field, expected in expected_tuple.items():
        if wrapper.get(field) != expected:
            fail(f"predecessor replay independent tuple mismatch: {field}")

    if wrapper.get("predecessor_source_semantics") != "frozen-v1":
        fail("predecessor replay source semantics drift")
    if wrapper.get("replay_environment_acquisition") != "successor-locked":
        fail("predecessor replay acquisition boundary drift")
    if wrapper.get("historical_environment_byte_identity_claimed") is not False:
        fail("predecessor replay historical byte-identity overclaim")
    if wrapper.get("pester_expected_partition_reproduced") is not True:
        fail("predecessor replay partition reproduction flag is false")
    if wrapper.get("known_error_findings") != 0:
        fail("predecessor replay wrapper reports known-error findings")
    if wrapper.get("analyzer_findings") != 0:
        fail("predecessor replay wrapper reports analyzer findings")

    hosted = _strict_json(contents["hosted-ci-receipt.json"], "hosted-ci-receipt.json")
    known_error = _strict_json(contents["known-error-scan.json"], "known-error-scan.json")
    ps51_summary = _strict_json(contents["ps51-summary.json"], "ps51-summary.json")

    if hosted.get("schema_version") != 1 or hosted.get("status") != "passed":
        fail("frozen hosted receipt status/schema mismatch")
    if hosted.get("authority") != "nxb-v1-ci-hosted-v1":
        fail("frozen hosted receipt authority mismatch")
    if hosted.get("head_sha") != expected_predecessor_main_sha:
        fail("frozen hosted receipt predecessor head mismatch")
    if hosted.get("pester_version") != wrapper.get("pester_version"):
        fail("frozen hosted receipt Pester version mismatch")
    if hosted.get("psscriptanalyzer_version") != wrapper.get(
        "psscriptanalyzer_version"
    ):
        fail("frozen hosted receipt PSScriptAnalyzer version mismatch")
    hosted_python = hosted.get("python_version")
    if hosted_python not in (
        wrapper.get("python_version"),
        f"Python {wrapper.get('python_version')}",
    ):
        fail("frozen hosted receipt Python version mismatch")
    if hosted.get("known_error_authority") != "nxb-v1-ci-known-error-scan-v1":
        fail("frozen hosted receipt known-error authority mismatch")
    if hosted.get("known_error_findings") != 0:
        fail("frozen hosted receipt reports known-error findings")
    if hosted.get("analyzer_findings") != 0:
        fail("frozen hosted receipt reports analyzer findings")
    if hosted.get("analyzer_process_isolated") is not True:
        fail("frozen hosted receipt analyzer isolation flag is false")
    if hosted.get("production_release_updated") is not False:
        fail("frozen hosted receipt claims production release mutation")

    frozen_hosted_counts = {
        "ps7_passed": FROZEN_PS7_TOTAL,
        "ps7_total": FROZEN_PS7_TOTAL,
        "ps7_not_run": 0,
        "ps51_passed": FROZEN_PS51_PASSED,
        "ps51_total": FROZEN_PS7_TOTAL,
        "ps51_not_run": FROZEN_PS51_NOT_RUN,
        "ps51_excluded_tag": FROZEN_PS51_EXCLUDED_TAG,
        "ps51_expected_excluded": FROZEN_PS51_NOT_RUN,
    }
    for field, expected in frozen_hosted_counts.items():
        if hosted.get(field) != expected:
            fail(f"frozen hosted receipt partition mismatch: {field}")

    if known_error.get("schema_version") != 1 or known_error.get("status") != "passed":
        fail("frozen known-error scan status/schema mismatch")
    if known_error.get("authority") != "nxb-v1-ci-known-error-scan-v1":
        fail("frozen known-error scan authority mismatch")
    if known_error.get("finding_count") != 0:
        fail("frozen known-error scan contains findings")
    if known_error.get("failed_contracts") != []:
        fail("frozen known-error scan contains failed contracts")
    if not _all_empty_known_error_findings(known_error.get("findings")):
        fail("frozen known-error scan finding buckets are not empty")

    expected_summary = {
        "passed": FROZEN_PS51_PASSED,
        "failed": 0,
        "skipped": 0,
        "not_run": FROZEN_PS51_NOT_RUN,
        "total": FROZEN_PS7_TOTAL,
        "excluded_tag": FROZEN_PS51_EXCLUDED_TAG,
        "expected_excluded": FROZEN_PS51_NOT_RUN,
    }
    for field, expected in expected_summary.items():
        if ps51_summary.get(field) != expected:
            fail(f"frozen PS5.1 summary partition mismatch: {field}")

    ps7_xml = _xml_results(contents["pester-ps7.xml"], "pester-ps7.xml")
    ps51_xml = _xml_results(contents["pester-ps51.xml"], "pester-ps51.xml")
    if ps7_xml["total"] != FROZEN_PS7_TOTAL or ps7_xml["not-run"] != 0:
        fail("frozen PS7 NUnit partition mismatch")
    # Pester's NUnit 2.5 writer reports the executed PS5.1 count in total and
    # excluded tests separately in not-run. The JSON summary retains logical
    # discovery total 916.
    if (
        ps51_xml["total"] != FROZEN_PS51_PASSED
        or ps51_xml["not-run"] != FROZEN_PS51_NOT_RUN
    ):
        fail("frozen PS5.1 NUnit partition mismatch")

    if wrapper.get("production_boundary") != {
        "private_key_used": False,
        "signer_used": False,
        "tag_mutation": False,
        "release_mutation": False,
        "merge_mutation": False,
        "repository_protection_mutated": False,
    }:
        fail("predecessor replay production boundary is not claim-free")

    return {
        "authority": AUTHORITY,
        "status": "PREDECESSOR_REPLAY_ARTIFACT_VALIDATED",
        "admitted": False,
        "repository_mutated": False,
        "native_wpt_dispatch_performed": False,
        "production_mutation_claimed": False,
        "entry_count": len(EXPECTED_NAMES),
        "zip_sha256": outer_sha256,
        "artifact_name": expected_artifact_name,
        "predecessor_main_sha": expected_predecessor_main_sha,
        "predecessor_tree_sha": expected_predecessor_tree_sha,
        "observer_successor_head_sha": expected_observer_successor_head_sha,
        "run_id": expected_run_id,
        "run_attempt": expected_run_attempt,
        "wrapper_schema_validated": True,
        "wrapper_schema_sha256": WRAPPER_SCHEMA_SHA256,
        "schema_validator_version": schema_validator_version,
        "child_hash_bindings_validated": True,
        "frozen_hosted_receipt_validated": True,
        "frozen_known_error_scan_validated": True,
        "frozen_pester_partition_validated": True,
        "frozen_run_ps51_identity_validated": True,
        "production_boundary_validated": True,
        "frozen_partition": {
            "ps7_passed": FROZEN_PS7_TOTAL,
            "ps7_total": FROZEN_PS7_TOTAL,
            "ps51_passed": FROZEN_PS51_PASSED,
            "ps51_total": FROZEN_PS7_TOTAL,
            "ps51_not_run": FROZEN_PS51_NOT_RUN,
            "ps51_excluded_tag": FROZEN_PS51_EXCLUDED_TAG,
        },
        "unverified_gates": [
            "github_run_and_artifact_metadata_provenance",
            "detached_predecessor_worktree_cas",
            "runtime_and_package_byte_provenance",
            "successor_toolchain_acquisition_provenance",
            "a0_hosted_artifact_cross_binding",
        ],
    }


def main() -> int:
    parser = argparse.ArgumentParser(allow_abbrev=False)
    parser.add_argument(
        "--mode",
        choices=["external-binding-preflight"],
        required=True,
    )
    parser.add_argument("--zip", required=True)
    parser.add_argument("--schema-root", required=True)
    parser.add_argument("--expected-zip-sha256", required=True)
    parser.add_argument("--expected-predecessor-main-sha", required=True)
    parser.add_argument("--expected-predecessor-tree-sha", required=True)
    parser.add_argument("--expected-observer-successor-head-sha", required=True)
    parser.add_argument("--expected-run-id", type=int, required=True)
    parser.add_argument("--expected-run-attempt", type=int, required=True)
    parser.add_argument("--expected-artifact-name", required=True)
    parser.add_argument("--expected-predecessor-policy-sha256", required=True)
    args = parser.parse_args()

    report = inspect_predecessor_replay(
        Path(args.zip),
        Path(args.schema_root),
        args.expected_zip_sha256,
        args.expected_predecessor_main_sha,
        args.expected_predecessor_tree_sha,
        args.expected_observer_successor_head_sha,
        args.expected_run_id,
        args.expected_run_attempt,
        args.expected_artifact_name,
        args.expected_predecessor_policy_sha256,
    )
    print(
        json.dumps(
            report,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        )
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except PreflightError as exc:
        print(f"NXB_V11_PREDECESSOR_REPLAY_PREFLIGHT_ERROR: {exc}", file=sys.stderr)
        raise SystemExit(2)
